### ISSUE TITLE
Why the shape of wieght matrix in GCN is (160,200) not (160,160) like paper says?

### ISSUE THREAD

**Issue by Tony0726** [ContextScout/gcn_ner#15]
As the above title saying, the paper says W^k belongs to R^m*m, shouldn't the shape of wieght matrix in GCN is (embedding_size, embedding_size)?

**Comment by fractalego** [comment]
Hi! Which line of code are you referring to? And which equation number in the paper?

**Comment by Tony0726** [comment]
line 11 in ner_model.py
equation: 
![image](https://user-images.githubusercontent.com/71976699/141425089-05dddc59-d076-45f0-b35b-8ac2702d67ce.png)
![image](https://user-images.githubusercontent.com/71976699/141425128-9370cdfc-c7a9-4f69-a85a-172666f06f0a.png)

**Comment by Tony0726** [comment]
line 11 in ner_model.py
equation 1

**Comment by fractalego** [comment]
I see now thanks. The naming convention in the code diverges a bit from the one on the paper. What on the paper is called W (left and right) is called Atilde_fw and Atilde_bw in the code. Effectively the line that performs the GCN transformation is line 16

X1_fw = tf.nn.relu(tf.matmul(Atilde_fw, left_X1_fw))

Line 11 just describes a dense layer as a buffer between the output of the RNN and the GCN transformation.
I should have been more careful with the naming conventions. I believe this is due to me refactoring the code before publishing it.

In the end
h_k = W x + b
where x is the first input to the GCN

and 
h_{k+1} = ReLu(Atilde_fw h_k)

Sorry for the misalignment. I was playing around with the optimal embedding size for the GCN and adding a dense layer before the GCN.

**Comment by Tony0726** [comment]
That explains a lot. Thank you very much for your answer.
